### ISSUE TITLE
Using Lizzie with cloud based Leela

### ISSUE THREAD

**Issue by chris-hughes-SB** [featurecat/lizzie#320] opened 2018-07-09 15:10 UTC
Is it possible to hook up Lizzie to a cloud based Leela?

ie. running Leela on Google Colabrotory -- https://github.com/gcp/leela-zero/blob/master/COLAB.md

Running Leela on CPU only isn't great and would love to use the free GPU on offer

**Comment by dfannius** [comment] 2018-07-09 16:44
I haven't tried this specifically but I don't see why not. I currently run Leela Zero on a separate machine (with a GPU) through ssh. You should just be able to change the leelaz.engine-command parameter in config.txt.

**Comment by bvandenbon** [comment] 2018-08-03 11:54
Damn, I just asked the same question, overlooked this one.

**Comment by featurecat** [comment] 2018-08-03 11:58
I definitely heard people talking about this. search this repo issues for
"ssh"? I think someone gave a solution.

**Comment by bvandenbon** [comment] 2018-08-06 16:04
@featurecat  thanks, I guess this is the one:
https://github.com/featurecat/lizzie/issues/92

**Comment by bvandenbon** [comment] 2018-08-10 12:12
It works ! ;-) Running in Amazon AWS cloud engine with a p2.xlarge instance. (K80 gpu).

![running in the aws cloud](https://user-images.githubusercontent.com/20482760/43957225-6f0d1978-9ca7-11e8-8d98-b96571f61d4b.jpg)

**Comment by featurecat** [comment] 2018-08-10 12:25
you want lag buffer to be 0. that only. matters in times games. thread count could probably be higher but needs experimentation.

**Comment by OlivierBlanvillain** [comment] 2018-10-02 07:20
Duplicate of #92, closing.

**Closed by OlivierBlanvillain** 2018-10-02 07:20 UTC

**Comment by bvandenbon** [comment] 2019-01-06 12:11
#How to DIY 👎 

I took an ubuntu instance, and then cloned the github repository to it, installed dependencies, build it, downloaded a network file.

There is a section in the leela zero readme called "Example of compiling and running - Ubuntu & similar". That really describes it in detail. After that you can just run `leelaz -g -w network.gz`

Now, every time you launch your instance, it will have a different IP address, and that's a bit annoying. You could pay for a fixed IP, but actually it is possible to write a script and ask AWS what the IP is. 
I wrote mine in java, but now that I look back at it, it would have been easier in javascript I think.

Anyway, you still need to configure your lizzie to connect to leelazero.
In your `engine-command` setting put this:

    ssh.exe -i yourkey.pem ubuntu@yourinstance.amazonaws.com leela-zero/src/leelaz --weights leela-zero/network --gtp --lagbuffer 0 --threads 2

The ubuntu user has no password, but it needs a pem file to secure the connection, which you can download from the AWS console. Now, I personally had a lot of problems with the `ssh.exe` file of windows. Apparently there are different ways to install it, and on some computers I just can't get it to work. But on others it works straightaway.

Before you use it, you will probably need to connect one time just from a command prompt, because you need to confirm that the host is secure. (just enter "yes"). From that point on, windows adds the host of your amazon instance to a whitelist, and next time you won't have to do this again. But it's crucial to do this step manually, because lizzie won't be able to answer the yes/no question obviously.

Another issue, is the fact that lizzie wants to download the network file every time you launch lizzie. But actually that's not necessary because the local network file doesn't matter, it's the one that is hosted in your amazon instance that matters. - But I think you can disable this with some lizzie setting.

#Or use my new website 🥇 

I am working on a webbased GUI that uses both AWS and Google instances in the background. Aiming to get it released before the end of this month.

If you are curious, you can find some screenshots on my twitter:
https://twitter.com/gogobrugo/status/1079529880952410113
