### ISSUE TITLE
Lizzie should survive leelaz crashes

### ISSUE THREAD

**Issue by gjm11** [featurecat/lizzie#315] opened 2018-07-07 22:00 UTC
I've just had the following thing happen: I was reviewing a game using Lizzie, the leelaz process crashed, and Lizzie died too.

It seems like it ought to be possible for Lizzie to survive Leela's death (at which point it could e.g. give the user some indication of what's going on, and then either automatically or optionally start up a new leelaz process and load the game so far into it.

**Comment by hydrogenpi** [comment] 2018-07-07 22:39
I concur, I posted this a while back and after all this time I'm still getting crashes and it still hasn't been fixed

https://github.com/featurecat/lizzie/issues/140

**Comment by featurecat** [comment] 2018-07-08 08:45
True... I was hoping to make this change when I refactored Lizzie. I guess I don't have as much time this summer as I'd hoped. I would like to work on that in August / September but it depends on my work status.

This change is part of my high priority goal for Lizzie although it may take some time.

**Comment by featurecat** [comment] 2018-07-08 08:47
Also #140 was at least partially fixed by #298.

**Comment by OlivierBlanvillain** [comment] 2018-10-02 11:53
Duplicate of #140, closing.

**Closed by OlivierBlanvillain** 2018-10-02 11:53 UTC
