### ISSUE TITLE
I managed to get Lizzie working with ELF.

### ISSUE THREAD

**Issue by jillybob** [featurecat/lizzie#171] opened 2018-05-04 12:52 UTC
I downloaded Leelaz.exe from https://github.com/Ka-zam/leela-zero/releases

I extracted the kazam leela zero files into a folder, added (did not overwite) extra dlls from /next compile, then added in Lizzie files (did not overwrite).  ELF now works with Lizzie, however after a few moves (between 20-50) it seems like leelaz.exe crashes and no more moves made. saving the SGF , closing and opening up lizzie and reloading the SGF makes it work. Here are all the files you need. Just run lizzie.jar 

https://drive.google.com/open?id=1OR41jpovaUXkuTUQhNEgncEFxTZ0PxmW

I am not sure what causes pondering to stop working. I am hoping someone can debug.

**Comment by Tenukis** [comment] 2018-05-04 17:00
Crashed on start, I cant manage to run it.

**Comment by kris-computer-go** [comment] 2018-05-04 21:16
@featurecat It would be much appreciated if you take a look :)

**Comment by bittsitt** [comment] 2018-05-04 21:43
Combining extra dlls and adding lizzie files? Sounds like you've found a great recipe for making a crash... 

I think a better approach is to wait until elf support is added to official leela zero next branch (and confirmed to be working), and re-apply the Lizzie patch to that (note that I think the UTCSearch.cpp files included with Lizzie now needs to be merged, there have been other changes to that file in the latest next, so that might cause problems as well)

**Comment by featurecat** [comment] 2018-05-04 21:53
I haven't been getting any errors. I've been using it since yesterday. Did you copy and replace each dll that is included? also try renaming the opencl_tuning file so it gets re-generated.

**Comment by Tenukis** [comment] 2018-05-05 00:29
@featurecat 
can the new Leela0.14 soon be adaptet to your lizzie binary?

**Comment by featurecat** [comment] 2018-05-05 05:34
It already works. Could you give me the error message? Also please turn leelaz-output on in lizzie.properties.

**Comment by FeelF** [comment] 2018-05-05 11:30
@featurecat
Facebook ELF Open Go v0 weights http://zero.sjeng.org/networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz
Leela Zero 0.14 + AutoGTP v16 https://github.com/gcp/leela-zero/releases/tag/v0.14
- Support for converted ELF Open Go networks.

**Comment by Tenukis** [comment] 2018-05-05 13:44
@featurecat
When I start Lizzie posted above, it keeps loading "Leela Zero is loading" but then Java stops running with message leelaz.exe doesnt runs and windows closes (only CPU, win7 x64, newest Java).

**Comment by featurecat** [comment] 2018-05-08 05:11
This will become much easier when we add official support for Leela Zero 0.14. Until then (1-2 weeks from now), please use Ka-zam's fork of Leela Zero, as it was compiled to be compatible with Lizzie.

**Closed by featurecat** 2018-05-08 05:11 UTC
