### ISSUE TITLE
Have any plan to provide win32 version?

### ISSUE THREAD

**Issue by wonsiks** [featurecat/lizzie#286] opened 2018-06-05 07:42 UTC
I myself is running 64bit Windows so no problem with that.
But one of my friend wants to use Lizzie but he's using 32bit Windows so that he can't use Lizzie.

What if you compile Lizzie for win32?
Do you have any plan for that?

Cheers...

**Comment by GenjiWu** [comment] 2018-06-05 11:38
Have you tried to compile it by yourself？

**Comment by wonsiks** [comment] 2018-06-05 11:42
No, I have zero knowledge about computer programming.
It seems just impossible for me to do...
Maybe I could ask help to some of my friends probably...

**Comment by featurecat** [comment] 2018-06-05 12:09
currently I don't have the energy to pursue this. all you would need to do is compile Leela zero Next for 32 bits. lizzie itself will work with that Leela zero. someone on Leela zero or lizzie posted their build instructions. so you'll need to follow those instructions or find someone willing to do this for you and send the exe. 

the alternative is to wait for official Leela zero 0.16 to release (they do 32 bit builds, right?). then it will work by default. i haven't tested on a 32 bit machine but I think it will run. might still need to install VC++ redistributable also.

**Comment by wonsiks** [comment] 2018-06-05 12:14
I see.
And sorry to annoying you by asking this...
You did great things anyway...thanks for that.
Good luck with everything you do... ^^

**Comment by featurecat** [comment] 2018-06-05 12:38
it's not related to the 32 bits specifically, I just have no energy :(

**Comment by OlivierBlanvillain** [comment] 2018-10-02 11:36
Duplicate of #17.

**Closed by OlivierBlanvillain** 2018-10-02 11:36 UTC
