### ISSUE TITLE
How to save winrates?

### ISSUE THREAD

**Issue by zszqzzzf** [featurecat/lizzie#327] opened 2018-07-15 02:51 UTC
After analyse the game winrate,  could we save the winrates data into a text file?

**Comment by featurecat** [comment] 2018-07-15 05:39
unfortunately not yet. this is would be the next feature (with variation saving) I would like too.

**Comment by OlivierBlanvillain** [comment] 2018-10-02 12:00
Duplicate of #308.

**Closed by OlivierBlanvillain** 2018-10-02 12:00 UTC
